### ISSUE TITLE
Not working with Grav 1.6.6

### ISSUE THREAD

**Issue by jgate** [Sommerregen/grav-plugin-shortcodes#4]
Twig \ Error \ SyntaxError
An exception has been thrown during the compilation of a template ("preg_match_all(): Compilation failed: missing ) at offset 53") in "@Shortcodes:C:/xampp/htdocs/????/user/pages/home".
Previous exceptions
preg_match_all(): Compilation failed: missing ) at offset 53 (2)
